# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyze.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import template_pb2 as template__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ranalyze.proto\x12\x05types\x1a\x0c\x63ommon.proto\x1a\x0etemplate.proto\"m\n\x11\x41nalyzeApiRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x19\n\x11\x61nalyzeTemplateId\x18\x02 \x01(\t\x12/\n\x0f\x61nalyzeTemplate\x18\x03 \x01(\x0b\x32\x16.types.AnalyzeTemplate\">\n\nRecognizer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x65ntities\x18\x02 \x03(\t\x12\x10\n\x08language\x18\x03 \x01(\t\"O\n\x0e\x41nalyzeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12/\n\x0f\x61nalyzeTemplate\x18\x02 \x01(\x0b\x32\x16.types.AnalyzeTemplate\"R\n\x0f\x41nalyzeResponse\x12,\n\x0e\x61nalyzeResults\x18\x01 \x03(\x0b\x32\x14.types.AnalyzeResult\x12\x11\n\trequestId\x18\x02 \x01(\t\")\n\x15RecognizersAllRequest\x12\x10\n\x08language\x18\x03 \x01(\t\"F\n\x16RecognizersAllResponse\x12,\n\x11recognizerResults\x18\x01 \x03(\x0b\x32\x11.types.Recognizer2\x9e\x01\n\x0e\x41nalyzeService\x12\x38\n\x05\x41pply\x12\x15.types.AnalyzeRequest\x1a\x16.types.AnalyzeResponse\"\x00\x12R\n\x11GetAllRecognizers\x12\x1c.types.RecognizersAllRequest\x1a\x1d.types.RecognizersAllResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyze_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ANALYZEAPIREQUEST']._serialized_start=54
  _globals['_ANALYZEAPIREQUEST']._serialized_end=163
  _globals['_RECOGNIZER']._serialized_start=165
  _globals['_RECOGNIZER']._serialized_end=227
  _globals['_ANALYZEREQUEST']._serialized_start=229
  _globals['_ANALYZEREQUEST']._serialized_end=308
  _globals['_ANALYZERESPONSE']._serialized_start=310
  _globals['_ANALYZERESPONSE']._serialized_end=392
  _globals['_RECOGNIZERSALLREQUEST']._serialized_start=394
  _globals['_RECOGNIZERSALLREQUEST']._serialized_end=435
  _globals['_RECOGNIZERSALLRESPONSE']._serialized_start=437
  _globals['_RECOGNIZERSALLRESPONSE']._serialized_end=507
  _globals['_ANALYZESERVICE']._serialized_start=510
  _globals['_ANALYZESERVICE']._serialized_end=668
# @@protoc_insertion_point(module_scope)
