# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: anonymize-image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import template_pb2 as template__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61nonymize-image.proto\x12\x05types\x1a\x0c\x63ommon.proto\x1a\x0etemplate.proto\"\x99\x02\n\x18\x41nonymizeImageApiRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x11\n\timageType\x18\x02 \x01(\t\x12\x19\n\x11\x61nalyzeTemplateId\x18\x03 \x01(\t\x12 \n\x18\x61nonymizeImageTemplateId\x18\x04 \x01(\t\x12/\n\x0f\x61nalyzeTemplate\x18\x05 \x01(\x0b\x32\x16.types.AnalyzeTemplate\x12=\n\x16\x61nonymizeImageTemplate\x18\x06 \x01(\x0b\x32\x1d.types.AnonymizeImageTemplate\x12/\n\rdetectionType\x18\x07 \x01(\x0e\x32\x18.types.DetectionTypeEnum\"\xc4\x01\n\x15\x41nonymizeImageRequest\x12\x1b\n\x05image\x18\x01 \x01(\x0b\x32\x0c.types.Image\x12/\n\x08template\x18\x02 \x01(\x0b\x32\x1d.types.AnonymizeImageTemplate\x12/\n\rdetectionType\x18\x03 \x01(\x0e\x32\x18.types.DetectionTypeEnum\x12,\n\x0e\x61nalyzeResults\x18\x04 \x03(\x0b\x32\x14.types.AnalyzeResult\"5\n\x16\x41nonymizeImageResponse\x12\x1b\n\x05image\x18\x01 \x01(\x0b\x32\x0c.types.Image2_\n\x15\x41nonymizeImageService\x12\x46\n\x05\x41pply\x12\x1c.types.AnonymizeImageRequest\x1a\x1d.types.AnonymizeImageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'anonymize_image_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ANONYMIZEIMAGEAPIREQUEST']._serialized_start=63
  _globals['_ANONYMIZEIMAGEAPIREQUEST']._serialized_end=344
  _globals['_ANONYMIZEIMAGEREQUEST']._serialized_start=347
  _globals['_ANONYMIZEIMAGEREQUEST']._serialized_end=543
  _globals['_ANONYMIZEIMAGERESPONSE']._serialized_start=545
  _globals['_ANONYMIZEIMAGERESPONSE']._serialized_end=598
  _globals['_ANONYMIZEIMAGESERVICE']._serialized_start=600
  _globals['_ANONYMIZEIMAGESERVICE']._serialized_end=695
# @@protoc_insertion_point(module_scope)
