# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: anonymize-json.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import template_pb2 as template__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61nonymize-json.proto\x12\x05types\x1a\x0etemplate.proto\"\x92\x02\n\x17\x41nonymizeJsonApiRequest\x12\x0c\n\x04json\x18\x01 \x01(\t\x12\x14\n\x0cjsonSchemaId\x18\x02 \x01(\t\x12\x19\n\x11\x61nalyzeTemplateId\x18\x03 \x01(\t\x12\x1b\n\x13\x61nonymizeTemplateId\x18\x04 \x01(\t\x12\x35\n\x12jsonSchemaTemplate\x18\x05 \x01(\x0b\x32\x19.types.JsonSchemaTemplate\x12/\n\x0f\x61nalyzeTemplate\x18\x06 \x01(\x0b\x32\x16.types.AnalyzeTemplate\x12\x33\n\x11\x61nonymizeTemplate\x18\x07 \x01(\x0b\x32\x18.types.AnonymizeTemplate\"\xb9\x01\n\x14\x41nonymizeJsonRequest\x12\x0c\n\x04json\x18\x01 \x01(\t\x12-\n\njsonSchema\x18\x02 \x01(\x0b\x32\x19.types.JsonSchemaTemplate\x12/\n\x0f\x61nalyzeTemplate\x18\x03 \x01(\x0b\x32\x16.types.AnalyzeTemplate\x12\x33\n\x11\x61nonymizeTemplate\x18\x04 \x01(\x0b\x32\x18.types.AnonymizeTemplateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'anonymize_json_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ANONYMIZEJSONAPIREQUEST']._serialized_start=48
  _globals['_ANONYMIZEJSONAPIREQUEST']._serialized_end=322
  _globals['_ANONYMIZEJSONREQUEST']._serialized_start=325
  _globals['_ANONYMIZEJSONREQUEST']._serialized_end=510
# @@protoc_insertion_point(module_scope)
