# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x05types\",\n\nFieldTypes\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08minScore\x18\x02 \x01(\t\"q\n\rAnalyzeResult\x12\x0c\n\x04text\x18\x01 \x01(\t\x12 \n\x05\x66ield\x18\x02 \x01(\x0b\x32\x11.types.FieldTypes\x12\r\n\x05score\x18\x03 \x01(\x02\x12!\n\x08location\x18\x04 \x01(\x0b\x32\x0f.types.Location\"6\n\x08Location\x12\r\n\x05start\x18\x01 \x01(\x11\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x11\x12\x0e\n\x06length\x18\x03 \x01(\x11\"a\n\x05Image\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x11\n\timageType\x18\x02 \x01(\t\x12)\n\rBoundingboxes\x18\x03 \x03(\x0b\x32\x12.types.Boundingbox\x12\x0c\n\x04text\x18\x04 \x01(\t\"\x8c\x01\n\x0b\x42oundingbox\x12\x11\n\txLocation\x18\x01 \x01(\x02\x12\r\n\x05width\x18\x02 \x01(\x02\x12\x11\n\tyLocation\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\x12\x0c\n\x04text\x18\x05 \x01(\t\x12\x15\n\rstartPosition\x18\x06 \x01(\x11\x12\x13\n\x0b\x65ndPosition\x18\x07 \x01(\x11*\x95\x02\n\x0e\x46ieldTypesEnum\x12\x0f\n\x0b\x43REDIT_CARD\x10\x00\x12\n\n\x06\x43RYPTO\x10\x01\x12\r\n\tDATE_TIME\x10\x02\x12\x0f\n\x0b\x44OMAIN_NAME\x10\x03\x12\x11\n\rEMAIL_ADDRESS\x10\x04\x12\r\n\tIBAN_CODE\x10\x05\x12\x0e\n\nIP_ADDRESS\x10\x06\x12\x07\n\x03NRP\x10\x07\x12\x0c\n\x08LOCATION\x10\x08\x12\n\n\x06PERSON\x10\t\x12\x10\n\x0cPHONE_NUMBER\x10\n\x12\x12\n\x0eUS_BANK_NUMBER\x10\x0b\x12\x15\n\x11US_DRIVER_LICENSE\x10\x0c\x12\x0b\n\x07US_ITIN\x10\r\x12\x0f\n\x0bUS_PASSPORT\x10\x0e\x12\n\n\x06US_SSN\x10\x0f\x12\n\n\x06UK_NHS\x10\x10*;\n\x11\x44\x65tectionTypeEnum\x12\x07\n\x03OCR\x10\x00\x12\r\n\tAZURE_OCR\x10\x01\x12\x0e\n\nAZURE_FACE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FIELDTYPESENUM']._serialized_start=483
  _globals['_FIELDTYPESENUM']._serialized_end=760
  _globals['_DETECTIONTYPEENUM']._serialized_start=762
  _globals['_DETECTIONTYPEENUM']._serialized_end=821
  _globals['_FIELDTYPES']._serialized_start=23
  _globals['_FIELDTYPES']._serialized_end=67
  _globals['_ANALYZERESULT']._serialized_start=69
  _globals['_ANALYZERESULT']._serialized_end=182
  _globals['_LOCATION']._serialized_start=184
  _globals['_LOCATION']._serialized_end=238
  _globals['_IMAGE']._serialized_start=240
  _globals['_IMAGE']._serialized_end=337
  _globals['_BOUNDINGBOX']._serialized_start=340
  _globals['_BOUNDINGBOX']._serialized_end=480
# @@protoc_insertion_point(module_scope)
