# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ocr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tocr.proto\x12\x05types\x1a\x0c\x63ommon.proto\")\n\nOcrRequest\x12\x1b\n\x05image\x18\x01 \x01(\x0b\x32\x0c.types.Image\"*\n\x0bOcrResponse\x12\x1b\n\x05image\x18\x01 \x01(\x0b\x32\x0c.types.Image2>\n\nOcrService\x12\x30\n\x05\x41pply\x12\x11.types.OcrRequest\x1a\x12.types.OcrResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ocr_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OCRREQUEST']._serialized_start=34
  _globals['_OCRREQUEST']._serialized_end=75
  _globals['_OCRRESPONSE']._serialized_start=77
  _globals['_OCRRESPONSE']._serialized_end=119
  _globals['_OCRSERVICE']._serialized_start=121
  _globals['_OCRSERVICE']._serialized_end=183
# @@protoc_insertion_point(module_scope)
