# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recognizers_store.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17recognizers_store.proto\x12\x05types\"5\n\x07Pattern\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05regex\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\"\x90\x01\n\x11PatternRecognizer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x65ntity\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12 \n\x08patterns\x18\x04 \x03(\x0b\x32\x0e.types.Pattern\x12\x11\n\tblacklist\x18\x05 \x03(\t\x12\x16\n\x0e\x63ontextPhrases\x18\x06 \x03(\t\"J\n\x1fRecognizerInsertOrUpdateRequest\x12\'\n\x05value\x18\x01 \x01(\x0b\x32\x18.types.PatternRecognizer\"\'\n\x17RecognizerDeleteRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"$\n\x14RecognizerGetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1a\n\x18RecognizersGetAllRequest\"\x1a\n\x18RecognizerGetHashRequest\"\x1a\n\x18RecognizersStoreResponse\"G\n\x16RecognizersGetResponse\x12-\n\x0brecognizers\x18\x01 \x03(\x0b\x32\x18.types.PatternRecognizer\"1\n\x16RecognizerHashResponse\x12\x17\n\x0frecognizersHash\x18\x01 \x01(\t2\x8c\x04\n\x17RecognizersStoreService\x12X\n\x0b\x41pplyInsert\x12&.types.RecognizerInsertOrUpdateRequest\x1a\x1f.types.RecognizersStoreResponse\"\x00\x12X\n\x0b\x41pplyUpdate\x12&.types.RecognizerInsertOrUpdateRequest\x1a\x1f.types.RecognizersStoreResponse\"\x00\x12P\n\x0b\x41pplyDelete\x12\x1e.types.RecognizerDeleteRequest\x1a\x1f.types.RecognizersStoreResponse\"\x00\x12H\n\x08\x41pplyGet\x12\x1b.types.RecognizerGetRequest\x1a\x1d.types.RecognizersGetResponse\"\x00\x12O\n\x0b\x41pplyGetAll\x12\x1f.types.RecognizersGetAllRequest\x1a\x1d.types.RecognizersGetResponse\"\x00\x12P\n\x0c\x41pplyGetHash\x12\x1f.types.RecognizerGetHashRequest\x1a\x1d.types.RecognizerHashResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recognizers_store_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PATTERN']._serialized_start=34
  _globals['_PATTERN']._serialized_end=87
  _globals['_PATTERNRECOGNIZER']._serialized_start=90
  _globals['_PATTERNRECOGNIZER']._serialized_end=234
  _globals['_RECOGNIZERINSERTORUPDATEREQUEST']._serialized_start=236
  _globals['_RECOGNIZERINSERTORUPDATEREQUEST']._serialized_end=310
  _globals['_RECOGNIZERDELETEREQUEST']._serialized_start=312
  _globals['_RECOGNIZERDELETEREQUEST']._serialized_end=351
  _globals['_RECOGNIZERGETREQUEST']._serialized_start=353
  _globals['_RECOGNIZERGETREQUEST']._serialized_end=389
  _globals['_RECOGNIZERSGETALLREQUEST']._serialized_start=391
  _globals['_RECOGNIZERSGETALLREQUEST']._serialized_end=417
  _globals['_RECOGNIZERGETHASHREQUEST']._serialized_start=419
  _globals['_RECOGNIZERGETHASHREQUEST']._serialized_end=445
  _globals['_RECOGNIZERSSTORERESPONSE']._serialized_start=447
  _globals['_RECOGNIZERSSTORERESPONSE']._serialized_end=473
  _globals['_RECOGNIZERSGETRESPONSE']._serialized_start=475
  _globals['_RECOGNIZERSGETRESPONSE']._serialized_end=546
  _globals['_RECOGNIZERHASHRESPONSE']._serialized_start=548
  _globals['_RECOGNIZERHASHRESPONSE']._serialized_end=597
  _globals['_RECOGNIZERSSTORESERVICE']._serialized_start=600
  _globals['_RECOGNIZERSSTORESERVICE']._serialized_end=1124
# @@protoc_insertion_point(module_scope)
